---
version: "2.1"
services:
  cuda-starter:
    image: solomspd/cuda-starter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - DEFAULT_WORKSPACE=/config/workspace
    ports:
      - 8443:8443
      - 22:22
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
